# Generated by Django 5.2.7 on 2026-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='predicted_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
